/**
 * IndexSearch.js
 *
 * author     -->  redcrow (jittagorn pitakmetagoon)
 * create on  -->  26/08/2013
 * website    -->  na5cent.blogspot.com
 * 
 * version    -->  1.0
 * version    -->  2.0 (multiple search keyword : AND search operation)
 * 
 * License    ---> Apache License
 * Version 2.0, January 2004 (http://www.apache.org/licenses/LICENSE-2.0)
 * 
 * 
 * 
 * update 13/12/2013 : add integrate period algorithm (document : http://na5cent.blogspot.com/2013/12/integrate-period-algorithm-javascript.html)
 */

window.IndexSearch=window.IndexSearch||function(){function p(a){return k(a)||0===a.length}function v(a,b,c){if(k(a))return-1;g(b,"String")&&(a=a.toLowerCase(),b=b.toLowerCase());return b.indexOf(a,k(c)?0:c)}function x(a){return a=a.replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}function f(a,b,c){if(!k(a)&&g(b,"Function"))for(var l in a)if(!1===b.call(c,a[l],l))return!1;return!0}function g(a,b){return Object.prototype.toString.call(a)==="[object "+b+"]"}function k(a){return g(a,
"Undefined")}function r(a){var b=0,c;for(c in a)b+=1;return b}function w(a){var b=parseFloat(a),c=parseInt(a);return 0===b-c?c:(new Number(a)).toFixed(2)}var D=function(){function a(a,b){if(!g(a,"String"))throw Error("constructor of Interface class require first argument is 'string', but is '"+typeof a+"'.");if(!g(b,"Array"))throw Error("constructor of Interface class require second argument is 'array of string', but is '"+typeof b+"'.");}function b(a,b){if(!g(a,"String"))throw Error("constructor of Interface class require second argument is 'array of string', but method index "+
b+" is not 'string', is '"+typeof a+"'.");return a}return function(c,l){if(2!==arguments.length)throw Error("constructor of Interface class require 2 arguments : Interface({string} name, {string[]} method names");a(c,l);for(var e=[],n=0;n<l.length;n++){var d=b(l[n],n);e.push(d)}this.getName=function(){return c};this.getMethods=function(){return e}}}();D.ensureImplements=function(a,b){if(2!==arguments.length)throw Error("Interface.ensureImplements require 2 arguments : Interface.ensureImplement({object} obj, {interface[]} interfaces).");
if(!g(a,"Object"))throw Error("first argument of Interface.ensureImplements is not 'object', but is '"+typeof a+"'.");if(!g(b,"Array"))throw Error("second argument of Interface.ensureImplements is not 'array of interface', but is '"+typeof b+"'.");for(var c=0;c<b.length;c++){var l=b[c];if(l.constructor!==D)throw Error("second argument of Interface.ensureImplements index "+c+" is not interface.");var e=l.getMethods(),n;for(n in e){var d=e[n];if(k(a[d]))throw Error("implementation class is not define method '"+
d+"' of Interface '"+l.getName()+"'.");if(!g(a[d],"Function"))throw Error("implementation class define '"+d+"' is not 'method', but is '"+typeof a[d]+"'.");}}};var E=function(a){var b=a.totalPosition||0,c=a.totalSentence||0,l=a.content||{nodes:{}},e=a.suggestions||[];this.getTotalPosition=function(){return b};this.getTotalSentence=function(){return c};this.getContent=function(){return l};this.getSuggestions=function(){return e}},A=function(a,b){var c=a,l=b;this.getStart=function(){return c};this.getEnd=
function(){return l};this.setStart=function(a){c=a};this.setEnd=function(a){l=a};this.equals=function(a){return a.getStart()===c&&a.getEnd()===l?!0:!1};this.toString=function(){return"period {"+c+", "+l+"}"}},C=function(){function a(){var a=[];f(l,function(d){a.push(d)});return a}function b(){e=a().sort(function(a,d){return a.getStart()===d.getStart()?a.getEnd()-d.getEnd():a.getStart()-d.getStart()})}function c(a){for(var d in e)e[d].equals(a)&&delete e[d]}var l={},e;this.addPeriod=function(a){var d;
d=a.getStart()+":"+a.getEnd();k(l[d])&&(l[d]=a);return this};this.addAllPeriods=function(a){p(a)||f(a,function(a){this.addPeriod(a)},this);return this};this.integrate=function(){b();if(1<e.length)for(var a=1;a<e.length;a++){var d=e[a-1],m=e[a];m.getStart()<d.getEnd()&&m.setStart(d.getEnd())}if(1<e.length)for(a=1;a<e.length;a++)for(d=e[a],m=a+1;m<e.length;m++){var h=e[m],q;if(q=!k(d))if(q=!k(h))if(q=h,!(q=q.getStart()>=q.getEnd())){q=h;var G=d;q=q.getStart()>=G.getStart()&&q.getEnd()<=G.getEnd()}q&&
c(h)}if(1<e.length)for(a=1;a<e.length;a++)d=e[a-1],m=e[a],k(m)||k(d)||m.getStart()!==d.getEnd()||(m.setStart(d.getStart()),c(d),a--);return e}},B=function(a){var b=a||"",c=0;this.split=function(){var a=[],e=b.split(" ");f(e,function(b){p(b)||(a.push(b),c+=1)});return a};this.getKeywordSize=function(){return c}},y=function(a){function b(a,b){var d=new C,m=new B(b);f(m.split(),function(h){if(p(h))return!0;for(var b=h.length,m=0,c=0;;){c=v(h,a,c);if(-1===c)break;m=c;c+=b;d.addPeriod(new A(m,c))}});return d.integrate()}
var c=0,l=0;this.getTotalSentence=function(){return c};this.resetTotalSentence=function(){c=0};this.getTotalHighlight=function(){return l};this.resetTotalHighlight=function(){l=0};this.resetTotal=function(){c=l=0};this.highlight=function(e,k){c+=1;var d=x(k),m=b(d,e),h=0;f(m,function(b){var m=b.getStart()+h,c=b.getEnd()+h;b=d.substring(0,m);var m=d.substring(m,c),e='<span class="'+a+'">'+m+"</span>",c=d.substring(c);d=b+e+c;h=h+e.length-m.length;l+=1});return d}},I=new D("IndexStore",["writeIndex",
"readIndex","addDictionary","getDictionaries","getIndexs"]),J=function(a){function b(a,b){var h=c(a);return l(h,b)}function c(a){var b={};f(a,function(a){f(a,function(a){k(b[a])&&(b[a]=0);b[a]+=1})});return b}function l(a,b){var h=[];f(a,function(a,d){a>=b&&h.push(d)});return h}var e=a;if(k(e)||1>e)e=1;var n=[];for(a=1;a<=e;a++)n[a]={};this.writeIndex=function(a,b){k(b)||f(n,function(h){f(h,function(h){f(h,function(h,c){-1!==v(c,b)&&-1===v(a,h)&&h.push(a)})})})};this.readIndex=function(a){var c={};
a=new B(a);f(a.split(),function(a){f(this.getDictionaries(a),function(b,d){-1!==v(a,d)&&(k(c[a])&&(c[a]={}),f(b,function(b){c[a][b]=b}))})},this);return b(c,a.getKeywordSize())};this.addDictionary=function(a){a=a.trim().toLowerCase();p(a)||f(n,function(b,c){if(a.length>=c){var e=a.substring(0,c);k(b[e])&&(b[e]={});k(b[e][a])&&(b[e][a]=[])}})};this.getDictionaries=function(a){if(p(a))return{};a=new B(a);var b={};f(a.split(),function(a){var c=b;a.length<=e?a=n[a.length][a]:(a=a.substring(0,e),a=n[e][a]);
for(var d in a)c[d]=a[d]});k(b)&&(b={});return b};this.getIndexs=function(){return n}},K=function(a){this.writeIndex=function(b,c){a.writeIndex(b,c)};this.addDictionary=function(b){a.addDictionary(b)}},L=function(a){this.readIndex=function(b){return a.readIndex(b)};this.getDictionaries=function(b){return a.getDictionaries(b)};this.getIndexs=function(){return a.getIndexs()}},M=function(a){function b(a){for(var b={},c=0;c<a.length;c++){var d=a.charAt(c);k(b[d])&&(b[d]={duplicate:0,position:0});b[d].duplicate+=
1;b[d].position+=c}return b}function c(a,c){var q=[],n=(new B(a)).split();f(n,function(B){return f(l,function(l,f){var s;a:{for(s in n)if(n[s]===f){s=!0;break a}s=!1}if(s=!s){var g;a:{s=q;for(g in s)if(s[g].word===f){g=!0;break a}g=!1}s=!g}if(s){s=b(B);var t,u=b(f);g=0;for(t in s){k(u[t])&&(u[t]={duplicate:0,position:0});var z=s[t],y=u[t],z=z.duplicate+z.position,y=y.duplicate+y.position;if(0!==z&&0!==y){var v=(y+z)/2;g=z>=y?g+y/v:g+z/v}}t=(r(s)+r(u))/2;t=g/t*100;if(t>=c&&(g=e.highlight(a,f),p(g)&&
(g=f),q.push({keywordMatch:B,word:f,highlight:g,percent:w(t)}),q.length===d))return!1}})});return q=q.sort(function(a,b){return b.percent-a.percent})}var l=a.dictionary,e=a.highlighter,n=a.percentSuggest||60,d=a.suggestionsSize||10;this.getSuggestionsWhenSearchFound=function(a){return c(a,0)};this.getSuggestionsWhenSearchNotFound=function(a){return c(a,n)}};return function(a){function b(){for(var a in H)x.addDictionary(H[a]);c(h);for(var b in h.nodes)l(0,b,h.nodes[b]);for(var d in z)delete z[d]}function c(a){for(var b in q){var d=
a[q[b]];if(!p(d)){var d=N(d),e=void 0;for(e in d)x.addDictionary(d[e])}}a=a.nodes;if(!p(a))for(var h in a)c(a[h])}function l(a,b,c){e(c,function(a){x.writeIndex(b,a)});c.level="level-"+a;c.index=b+"";c=c.nodes;if(!p(c))for(var d in c)l(a+1,b+s+d,c[d])}function e(a,b){for(var c in q){var d=q[c],e=z[d];k(e)&&(e={},z[d]=e);var h=e[a[d]];k(h)&&(h=!0,e[a[d]]=h,b(a[d]))}}function n(){var a={};f(F,function(b){var c=b.word[0];k(a[c])&&(a[c]=[]);a[c].push(b.word)});var b=(new B(u)).split();f(a,function(a){a=
a[0];for(var c in b)if(b[c][0]===a[0]&&(a.length<b[c].length||-1===v(b[c],a))){b[c]=a;break}});return b.join(" ")}function d(){return new E({totalPosition:r.getTotalHighlight(),totalSentence:r.getTotalSentence(),content:t,suggestions:F})}function m(){var a=A.readIndex(u),b;for(b in a){var c=a[b].split(s),d=h,e=t,l=void 0;for(l in c){var g=c[l];if(p(g))break;var d=d.nodes[g],f=e.nodes[g];if(k(f)){var f=d,m={},n=void 0;for(n in f)if("nodes"!==n){m[n]=f[n];for(var B in q)if(n===q[B]){var y=r.highlight(u,
m[n]);p(y)||(m[n+C]=y)}}f=m;e.nodes[g]=f}k(f.nodes)&&(f.nodes=[]);e=f}}}if(k(a))throw Error("require {object} settings");var h=a.repository;if(k(h))throw Error("require {repository} settings.repository");if(!g(h,"Object"))throw Error("require {repository} settings.repository is root node object");var q=a.indexOnFields||[];if(p(q))throw Error("require index field on {string[]} : settings.indexOnFields");if(-1!==v("nodes",q))throw Error("field name 'nodes' in {string[]} : settings.indexOnFields is reserved word");
var r=new y(a.highlightClass||"keyword-highlight"),w=a.indexStore||new J(a.maximumDictionaryKeySize||3);D.ensureImplements(w,[I]);var x=new K(w),A=new L(w),s=a.indexSeparator||"/",C=a.postfixFieldNameHighlight||"Highlight",t,u="",z={},H=a.additionalDictionaries||[],F=[],O=a.suggestionsSize,P=a.percentSuggest,N=a.stopword||function(a){a=k(a)?"":a.replace(/\(/g," ").replace(/\)/g," ").replace(/\,/g," ").replace(/\//g," ").replace(/\\/g," ").replace(/\:/g," ").replace(/\./g," ").replace(/\>/g," ").replace(/\</g,
" ").replace(/\[/g," ").replace(/\]/g," ").replace(/\+/g," ").replace(/\=/g," ").replace(/\;/g," ");return a.split(" ")};b();this.reIndex=function(a){h=a;b()};this.getKeyword=function(){return u};this.getRepository=function(){return h};this.getIndexs=function(){return A.getIndexs()};this.clear=function(){u="";return new E({content:h})};this.search=function(a){if(p(a))return new E({content:h});a=a.trim().toLowerCase();if(u===a)return d();r.resetTotal();t={nodes:[]};F=[];u=a;m();F=(new M({dictionary:A.getDictionaries(u),
suggestionsSize:O,percentSuggest:P,highlighter:r})).getSuggestionsWhenSearchFound(u);p(t.nodes)&&!p(F)&&(u=n(),m());return d()}}}();window.Blogger=window.Blogger||{};window.Blogger.pullRepositoryFromBlog=function(p,v){var x=document.createElement("script");x.type="text/javascript";x.src=p+"/feeds/posts/default?max-results=10000&alt=json-in-script&callback=blogFeedCallback";x.onload=function(){v(window.blogFeedRepository)};document.getElementsByTagName("head")[0].appendChild(x)};
function blogFeedCallback(p){function v(f){f=f.sort(function(f,g){return f.published>g.published})}function x(f){var k=g.nodes,p;for(p in k){var r=k[p];if(r.name===f)return r}return null}function f(f){f=f.link;for(var g in f)if("alternate"===f[g].rel)return f[g].href;return""}var g={nodes:[]},k=p.feed,r=k.category,w;for(w in r)p=r[w],g.nodes.push({name:p.term,link:"/search/label/"+encodeURIComponent(p.term)});k=k.entry;for(w in k){r=k[w];r.title.$t;var D=r.category,E;for(E in D){p=x(D[E].term);var A=
p.nodes;A||(A=[]);var C={name:r.title.$t,published:new Date(r.published.$t),link:f(r),nodes:[]};5>w&&(C.newPost=!0);A.push(C);p.nodes=A}}(function(f){f=f.sort(function(f,g){return f.name.localeCompare(g.name)})})(g.nodes);for(w in g.nodes)C=g.nodes[w],v(C.nodes);window.blogFeedRepository=g};



